# Generated by Django 2.1.3 on 2020-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0002_article_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
