# Generated by Django 2.1.3 on 2020-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0003_auto_20200910_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
