# Generated by Django 2.1.3 on 2020-09-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0004_auto_20200910_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
